apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: staging-yas-services
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: "3"
spec:
    generators:
        - git:
              repoURL: https://github.com/powerstomp/yas-deployment.git
              revision: HEAD
              files:
                  - path: gitops/children/environments/staging/services.yaml
    template:
        metadata:
            name: "staging-{{ name }}"
            namespace: argocd
            annotations:
                argocd-image-updater.argoproj.io/image-list: "backend={{ repository }},ui={{ repository }}"
                argocd-image-updater.argoproj.io/backend.update-strategy: semver
                argocd-image-updater.argoproj.io/backend.helm.name: backend.image.repository
                argocd-image-updater.argoproj.io/backend.helm.tag: backend.image.tag
                argocd-image-updater.argoproj.io/ui.update-strategy: semver
                argocd-image-updater.argoproj.io/ui.helm.name: ui.image.repository
                argocd-image-updater.argoproj.io/ui.helm.tag: ui.image.tag
                argocd-image-updater.argoproj.io/git-config: |
                    writeBackTarget: helmvalues:./gitops/children/environments/staging/services.yaml
                argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/image-updater-creds"
        spec:
            project: staging
            source:
                repoURL: https://github.com/powerstomp/yas-deployment.git
                targetRevision: HEAD
                path: "charts/{{ name }}"
                helm:
                    values: |
                        backend:
                          image:
                            repository: {{ repository }}
                            tag: {{ tag }}
                            pullPolicy: Always
                          ingress:
                            host: {{ host }}.staging.yas.local.com
                        ui:
                          image:
                            repository: {{ repository }}
                            tag: {{ tag }}
                            pullPolicy: Always
                          extraEnvs:
                            - name: API_BASE_PATH
                              value: http://storefront.staging.yas.local.com/api
                        image:
                          repository: {{ repository }}
                          tag: {{ tag }}
                        ingress:
                          host: {{ host }}.staging.yas.local.com
            destination:
                server: https://kubernetes.default.svc
                namespace: yas-staging
            syncPolicy:
                automated:
                    prune: true
                    selfHeal: true
                managedNamespaceMetadata:
                    labels:
                        istio.io/dataplane-mode: ambient
                syncOptions:
                    - CreateNamespace=true
                    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: staging-yas-configuration
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: "3"
spec:
    project: staging
    source:
        repoURL: https://github.com/powerstomp/yas-deployment.git
        targetRevision: HEAD
        path: charts/yas-configuration
        helm:
            values: |
                mediaApplicationConfig:
                    yas:
                        publicUrl: http://api.staging.yas.local.com/media
                paymentPaypalApplicationConfig:
                    yas:
                        public:
                            url: http://storefront.staging.yas.local.com/complete-payment
    destination:
        server: https://kubernetes.default.svc
        namespace: yas-staging
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        managedNamespaceMetadata:
            labels:
                istio.io/dataplane-mode: ambient
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
