apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akhq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: akhq
    repoURL: https://akhq.io/
    targetRevision: 0.27.0
    helm:
      values: |
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        configuration:
          akhq:
            server:
              access-log:
                enabled: false
                name: org.akhq.log.access
            connections:
              kafka-connection:
                properties:
                  bootstrap.servers: kafka-cluster-kafka-bootstrap:9092
                connect:
                  - name: debezium-connect-cluster
                    url: http://debezium-connect-cluster-connect-api:8083
        hostname: &hostname akhq.yas.local.com
        ingress:
          enabled: true
          annotations: {}
          paths:
            - /
          hosts:
            - *hostname
          tls: []
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
