apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: tempo
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: "2"
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: infrastructure
    sources:
        - ref: values
          repoURL: https://github.com/powerstomp/yas-deployment.git
          targetRevision: HEAD
        - chart: tempo
          repoURL: https://grafana.github.io/helm-charts
          targetRevision: 1.24.4
          helm:
              valueFiles:
                  - $values/deploy/observability/tempo.values.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: observability
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        managedNamespaceMetadata:
            labels:
                istio.io/dataplane-mode: ambient
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
