backend:
    image:
        repository: ghcr.io/powerstomp/yas-rating
        tag: latest

    nameOverride: rating
    fullnameOverride: rating
    databaseName: rating
    ingress:
        enabled: false
