helm:
  parameters:
  - name: image.name
    value: swaggerapi/swagger-ui
    forcestring: true
  - name: image.tag
    value: latest@sha256:135a9ced4005a947bbb1757bc509309d88519d985aa0f5616f4fdfab1eba6ff6
    forcestring: true
