backoffice-bff:
  repository: ghcr.io/powerstomp/yas-backoffice-bff
  tag: "latest"
  host: backoffice
backoffice-ui:
  repository: ghcr.io/powerstomp/yas-backoffice
  tag: "latest"
  host: backoffice
cart:
  repository: ghcr.io/powerstomp/yas-cart
  tag: "latest"
  host: api
customer:
  repository: ghcr.io/powerstomp/yas-customer
  tag: "latest"
  host: api
inventory:
  repository: ghcr.io/powerstomp/yas-inventory
  tag: "latest"
  host: api
location:
  repository: ghcr.io/powerstomp/yas-location
  tag: "latest"
  host: api
media:
  repository: ghcr.io/powerstomp/yas-media
  tag: "latest"
  host: api
order:
  repository: ghcr.io/powerstomp/yas-order
  tag: "latest"
  host: api
payment:
  repository: ghcr.io/powerstomp/yas-payment
  tag: "latest"
  host: api
product:
  repository: ghcr.io/powerstomp/yas-product
  tag: "latest"
  host: api
promotion:
  repository: ghcr.io/powerstomp/yas-promotion
  tag: "latest"
  host: api
rating:
  repository: ghcr.io/powerstomp/yas-rating
  tag: "latest"
  host: api
recommendation:
  repository: ghcr.io/powerstomp/yas-recommendation
  tag: "latest"
  host: api
sampledata:
  repository: ghcr.io/powerstomp/yas-sampledata
  tag: "latest"
  host: api
search:
  repository: ghcr.io/powerstomp/yas-search
  tag: "latest"
  host: api
storefront-bff:
  repository: ghcr.io/powerstomp/yas-storefront-bff
  tag: "latest"
  host: storefront
storefront-ui:
  repository: ghcr.io/powerstomp/yas-storefront
  tag: "latest"
  host: storefront
swagger-ui:
  repository: swaggerapi/swagger-ui
  tag: "v4.16.0"
  host: api
tax:
  repository: ghcr.io/powerstomp/yas-tax
  tag: "latest"
  host: api
webhook:
  repository: ghcr.io/powerstomp/yas-webhook
  tag: "latest"
  host: api
