- name: backoffice-bff
  repository: ghcr.io/powerstomp/yas-backoffice-bff
  tag: "latest"
  host: backoffice
- name: backoffice-ui
  repository: ghcr.io/powerstomp/yas-backoffice
  tag: "v1.0.3"
  host: backoffice
- name: cart
  repository: ghcr.io/powerstomp/yas-cart
  tag: "latest"
  host: api
- name: customer
  repository: ghcr.io/powerstomp/yas-customer
  tag: "latest"
  host: api
- name: inventory
  repository: ghcr.io/powerstomp/yas-inventory
  tag: "latest"
  host: api
- name: location
  repository: ghcr.io/powerstomp/yas-location
  tag: "latest"
  host: api
- name: media
  repository: ghcr.io/powerstomp/yas-media
  tag: "latest"
  host: api
- name: order
  repository: ghcr.io/powerstomp/yas-order
  tag: "latest"
  host: api
- name: payment
  repository: ghcr.io/powerstomp/yas-payment
  tag: "latest"
  host: api
- name: product
  repository: ghcr.io/powerstomp/yas-product
  tag: "latest"
  host: api
- name: promotion
  repository: ghcr.io/powerstomp/yas-promotion
  tag: "latest"
  host: api
- name: rating
  repository: ghcr.io/powerstomp/yas-rating
  tag: "latest"
  host: api
- name: recommendation
  repository: ghcr.io/powerstomp/yas-recommendation
  tag: "latest"
  host: api
- name: sampledata
  repository: ghcr.io/powerstomp/yas-sampledata
  tag: "latest"
  host: api
- name: search
  repository: ghcr.io/powerstomp/yas-search
  tag: "latest"
  host: api
- name: storefront-bff
  repository: ghcr.io/powerstomp/yas-storefront-bff
  tag: "latest"
  host: storefront
- name: storefront-ui
  repository: ghcr.io/powerstomp/yas-storefront
  tag: "latest"
  host: storefront
- name: swagger-ui
  repository: swaggerapi/swagger-ui
  tag: "v4.16.0"
  host: api
- name: tax
  repository: ghcr.io/powerstomp/yas-tax
  tag: "latest"
  host: api
- name: webhook
  repository: ghcr.io/powerstomp/yas-webhook
  tag: "latest"
  host: api
