helm:
  parameters:
  - name: image.name
    value: ghcr.io/powerstomp/yas-storefront
    forcestring: true
  - name: image.tag
    value: latest@sha256:f87ea0372694ac6f4742cb11e5a5452f8da9fd8a36704a3e1e771976d713a893
    forcestring: true
