apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
    name: staging
    namespace: argocd
spec:
    writeBackConfig:
        method: "git:secret:argocd/image-updater-creds"
        gitConfig:
            branch: "master"
            writeBackTarget: "helmvalues:./gitops/children/environments/staging/services.yaml"
    applicationRefs:
        - namePattern: "staging-*"
          useAnnotations: true
