apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: 3.4.0
    helm:
      values: |
        installCRDs: true
        # Disable operator — it runs in wave -1
        replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
