apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: grafana-operator
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: v5.0.2
    helm:
      values: |
        # CRDs-only
        replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
