apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 85.0.1
    helm:
      values: |
        crds:
          enabled: true
        # Disable everything else — we only want CRDs here
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeStateMetrics:
          enabled: false
        kubelet:
          enabled: false
        nodeExporter:
          enabled: false
        prometheus:
          enabled: false
        prometheus-node-exporter:
          enabled: false
        prometheus-pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
